Ogani/Models/HomeViewModel.cs
using Ogani.DataContext.Entities;

namespace Ogani.Models
{
    public class HomeViewModel
    {
        public List<Product> Products { get; set; } = new();
        public List<Category> Categories { get; set; } = new();
        public List<ProductImage>? ProductImages { get;  set; }
    }
}

Ogani/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Ogani.DataContext;
using Ogani.Models;
using System.Diagnostics;

namespace Ogani.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _dbContext;

        public HomeController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var products = _dbContext.Products.ToList();
            var categories = _dbContext.Categories.ToList();

            var homeViewModel = new HomeViewModel
            {
                Products = products,
                Categories = categories,
            };

            return View(homeViewModel);
        }
    }
}

Ogani/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ogani.DataContext;
using Ogani.Models;

namespace Ogani.Controllers
{

    public class ShopController : Controller
    {
        private readonly AppDbContext _dbContext;

        public ShopController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            var products = await _dbContext.Products.ToListAsync();
            var categories = await _dbContext.Categories.ToListAsync();

            var shopViewModel = new ShopViewModel
            {
                Products = products,
                Categories = categories
            };

            return View(shopViewModel);
        }
    }
}

Ogani/Views/Home/Index.cshtml
@using Ogani.DataContext.Entities
@model HomeViewModel

@{
    HomeViewModel model = Model;
    var products = model.Products;
    var categories = model.Categories;
}

<!-- Hero Section Begin -->
<section class="hero">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="hero__categories">
                    <div class="hero__categories__all">
                        <i class="fa fa-bars"></i>
                        <span>All departments</span>
                    </div>
                    <ul>
                        @foreach (var category in Model.Categories)
                        {
                            <li><a href="#">@category.Name</a></li>
                        }
                    </ul>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="hero__search">
                    <div class="hero__search__form">
                        <form action="#">
                            <div class="hero__search__categories">
                                All Categories
                                <span class="arrow_carrot-down"></span>
                            </div>
                            <input type="text" placeholder="What do yo u need?">
                            <button type="submit" class="site-btn">SEARCH</button>
                        </form>
                    </div>
                    <div class="hero__search__phone">
                        <div class="hero__search__phone__icon">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="hero__search__phone__text">
                            <h5>+65 11.188.888</h5>
                            <span>support 24/7 time</span>
                        </div>
                    </div>
                </div>
                <div class="hero__item set-bg" data-setbg="img/hero/banner.jpg">
                    <div class="hero__text">
                        <span>FRUIT FRESH</span>
                        <h2>Vegetable <br />100% Organic</h2>
                        <p>Free Pickup and Delivery Available</p>
                        <a href="#" class="primary-btn">SHOP NOW</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Hero Section End -->
<!-- Categories Section Begin -->
<section class="categories">
    <div class="container">
        <div class="row">
            <div class="categories__slider owl-carousel">
                @foreach (var category in Model.Categories)
                {
                    <div class="col-lg-3">
                        <div class="categories__item set-bg" data-setbg="/uploads/categories/@category.ImageUrl">
                            <h5><a href="#">@category.Name</a></h5>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>
<!-- Categories Section End -->
<!-- Featured Section Begin -->
<section class="featured spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>Featured Product</h2>
                </div>
                <div class="featured__controls">
                    <ul>
                        <li class="active" data-filter="*">All</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row featured__filter">

            @foreach (var product in Model.Products)
            {
                var categoryClass = product.Category?.Name?.ToLower().Replace(" ", "-") ?? "";

                <div class="col-lg-3 col-md-4 col-sm-6 mix @categoryClass">
                    <div class="featured__item">
                        <div class="featured__item__pic set-bg" data-setbg="/uploads/products/@product.ImageUrl">
                            <ul class="featured__item__pic__hover">
                                <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                                <li><a href="#"><i class="fa fa-shopping-cart"></i></a></li>
                            </ul>
                        </div>
                        <div class="featured__item__text">
                            <h6>
                                <a asp-controller="Shop" asp-action="Details" asp-route-id="@product.Id">
                                    @product.Name
                                </a>
                            </h6>
                            <h5>@product.Price.ToString("C")</h5>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</section>
<!-- Featured Section End -->
<!-- Banner Begin -->
<div class="banner">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="banner__pic">
                    <img src="~/img/banner/banner-1.jpg" alt="">
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="banner__pic">
                    <img src="~/img/banner/banner-2.jpg" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner End -->
<!-- Latest Product Section Begin -->
<section class="latest-product spad">
    <div class="container">
        <div class="row">
            @{
                var sections = new Dictionary<string, List<Product>>()
                        {
                        { "Latest Products", Model.Products.Take(6).ToList() },
                        { "Top Rated Products", Model.Products.Take(6).ToList() },
                        { "Review Products", Model.Products.Take(6).ToList() }
                        };

                List<List<Product>> SliceProducts(List<Product> products, int size)
                {
                    var slice = new List<List<Product>>();
                    for (int i = 0; i < products.Count; i += size)
                        slice.Add(products.Skip(i).Take(size).ToList());
                    return slice;
                }
            }

            @foreach (var productSection in sections)
            {
                <div class="col-lg-4 col-md-6">
                    <div class="latest-product__text">
                        <h4>@productSection.Key</h4>
                        <div class="latest-product__slider owl-carousel">

                            @foreach (var slice in SliceProducts(productSection.Value, 3))
                            {
                                <div class="latest-prdouct__slider__item">
                                    @foreach (var product in slice)
                                    {
                                        <a href="#" class="latest-product__item">
                                            <div class="latest-product__item__pic">
                                                <img src="~/uploads/products/@product.ImageUrl" alt="@product.Name">
                                            </div>
                                            <div class="latest-product__item__text">
                                                <h6>@product.Name</h6>
                                                <span>@product.Price.ToString("C")</span>
                                            </div>
                                        </a>
                                    }
                                </div>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
<!-- Blog Section Begin -->
<section class="from-blog spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title from-blog__title">
                    <h2>From The Blog</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="blog__item">
                    <div class="blog__item__pic">
                        <img src="~/img/blog/blog-1.jpg" alt="">
                    </div>
                    <div class="blog__item__text">
                        <ul>
                            <li><i class="fa fa-calendar-o"></i> May 4,2019</li>
                            <li><i class="fa fa-comment-o"></i> 5</li>
                        </ul>
                        <h5><a href="#">Cooking tips make cooking simple</a></h5>
                        <p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="blog__item">
                    <div class="blog__item__pic">
                        <img src="~/img/blog/blog-2.jpg" alt="">
                    </div>
                    <div class="blog__item__text">
                        <ul>
                            <li><i class="fa fa-calendar-o"></i> May 4,2019</li>
                            <li><i class="fa fa-comment-o"></i> 5</li>
                        </ul>
                        <h5><a href="#">6 ways to prepare breakfast for 30</a></h5>
                        <p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="blog__item">
                    <div class="blog__item__pic">
                        <img src="~/img/blog/blog-3.jpg" alt="">
                    </div>
                    <div class="blog__item__text">
                        <ul>
                            <li><i class="fa fa-calendar-o"></i> May 4,2019</li>
                            <li><i class="fa fa-comment-o"></i> 5</li>
                        </ul>
                        <h5><a href="#">Visit the clean farm in the US</a></h5>
                        <p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Section End -->